#name, main, version and api are required
name: InvSee
main: tschrock\InvSee\InvSee
version: 1.0.0-ALPHA1
api: [3.0.0-ALPA9, 3.0.0-ALPHA10]
load: POSTWORLD
author: VMPE Development Team
description: Look at a player's invenory to make sure they aren't using any banned / hacked items.
website: Not showing,
commands:
 invsee:
  description: "See a player's inventory"
  usage: "/invsee <player>"
  permission: invsee.check
permissions:
 invsee.check:
  description: "Allows the user to see a player's inventory"
  default: op
