#name, main, version and api are required
name: InvSee
main: tschrock\InvSee\InvSee
version: 0.0.2
api: [3.0.0-ALPHA10]

load: POSTWORLD
author: tschrock (tschrock123@gmail.com)
description: See a copy of a player's inventory
website: http://www.tschrock.net
commands:
 invsee:
  description: "See a player's inventory"
  usage: "/invsee <player>"
  permission: invsee.check
permissions:
 invsee.check:
  description: "Allows the user to see a player's inventory"
  default: op
